Item.destroy_all

# appetizers
Item.create(name: "Queso", description: "Homemade cheese dip with Mexican spices and pico de gallo", price: 9, category:"appetizers", imgURL: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/4/8/1/FNM_050114-Double-Chile-Queso-Dip-Recipe_s4x3.jpg.rend.hgtvcom.616.462.suffix/1397163257399.jpeg")
Item.create(name: "Flautas", description: "Ancho brisket, roasted red peppers and cheese, served with tomatillo salsa", price: 9, category:"appetizers", imgURL: "https://thefoodcharlatan.com/wp-content/uploads/2013/05/IMG_3194-e1367551208242.jpg")
Item.create(name: "Chicken Empanadas", description: "Served with tomatillo salsa and chipotle salsa rojo", price: 11, category:"appetizers", imgURL: "http://www.bemindfulbehuman.com/wp-content/uploads/MG_9411.chicken.empanadas.final1_.png")
Item.create(name: "Cheese Quesadilla",description: "Served with sour cream and guacamole and topped with fresh jalapenos", price: 9, category:"appetizers", imgURL: "https://cdn-image.foodandwine.com/sites/default/files/styles/medium_2x/public/201408-xl-pimento-cheese-quesadillas.jpg?itok=uqizsUaC")
Item.create(name: "Crispy Wings",description:  "Choices: Buffalo, BBQ, Soy Garlic, and Sweet Chili", price: 11, category:"appetizers", imgURL: "https://thebakermama.com/wp-content/uploads/2014/06/Crispy-Sweet-Spicy-Chicken-Wings-2-300x225.jpg")
Item.create(name: "Guacamole", description: "Made with only the freshest Michoacano avocado, onion and cilantro. Served with golden tortilla chips", price: 10, category:"appetizers", imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQClnMPpgjXvMqtpbkubcgmruFGS2dlXY_F4CpsriOG2Vz6vNgq")
Item.create(name: "Nachos", description: "Made with only the freshest Michoacano avocado, onion and cilantro. Served with golden tortilla chips", price: 11, category:"appetizers", imgURL: "https://www.kitchensanctuary.com/wp-content/uploads/2017/12/Crispy-Leftover-Turkey-Nachos-Recipe-square-FS.jpg")


# main
Item.create( name: "Chicken Enchiladas", description: "Tacos stuffed with chicken, coated in smooth salsa roja, verde or bandera and a touch of crema Mexicana, topped with lettuce, melted cheese, onion and avocado", price: 13, category:"main", imgURL: "https://images-gmi-pmc.edge-generalmills.com/e33eb988-2068-4a09-b07e-69f60ea2af3f.jpg")
Item.create( name: "Chile Enchiladas", description: "Chile marinated meat,oaxaca cheese, with, chipotles or jalapenos" , price: 10, category:"main", imgURL: "https://tmbidigitalassetsazure.blob.core.windows.net/secure/RMS/attachments/37/1200x1200/Cheddar-Beef-Enchiladas_exps21076_GB2919407B01_10_3bC_RMS.jpg")
Item.create( name: "Mar y Tierra", description: "A delicous combo of prime skirt steak cooked to your order and shrimp in a garlic sauce, served with mexican rice and beans", price: 23, category:"main", imgURL: "http://milenioplaza.com.co/wp-content/uploads/2018/02/mar-y-tierra.jpg")
Item.create( name: "Bistec Ranchero", description: "Steak cooked with jalapenos, white onions, tomatoes, sweet corn and mushrooms. Served with mexican rice refried beans and corn tortillas", price: 15, category:"main", imgURL: "https://www.mexicoenmicocina.com/wp-content/uploads/2018/04/bistec-ranchero-4.jpg")
Item.create( name: "Chiles Rellenos", description: "Roasted poblano pepper coated with an airy egg and topped with a tomato sauce , stuffed with your choice, served with rice beans and corn tortilla", price: 12, category:"main", imgURL: "https://static01.nyt.com/images/2018/12/12/dining/12davilarex1/merlin_147457293_04597239-7563-4b84-aa68-a9f1729e7111-articleLarge.jpg")
Item.create( name: "Pastor Tacos", description: "Topped with cilantro and onion, served with spicy green sauce and limes on corn tortillas, comes with 4 tacos", price: 10, category:"main", imgURL: "https://keviniscooking.com/wp-content/uploads/2017/04/Authentic-Tacos-Al-Pastor-square2.jpg")
Item.create( name: "Baja Tacos", description: "Topped with cilantro and red onion, served with spicy green sauce and limes on corn tortillas, comes with 4 tacos", price: 12, category:"main", imgURL: "https://www.billyparisi.com/wp-content/uploads/2012/07/fish-tacos-4.jpg")
Item.create( name: "Beef Tacos", description: "Topped with cilantro and red onion, served with spicy green sauce and limes on corn tortillas, comes with 4 tacos", price: 9, category:"main", imgURL: "https://hispanickitchen.com/wp-content/uploads/2017/01/classic-ground-beef-hardshell-tacos-3-2.jpg")
Item.create( name: "Vegetales Tacos", description: "Topped with cilantro and red onion, served with spicy green sauce and limes on corn tortillas, comes with 4 tacos", price: 9, category:"main", imgURL: "https://www.inspiredtaste.net/wp-content/uploads/2016/10/Veggie-Tacos-Recipe-2.jpg")
Item.create( name: "Grilled Chicken Tacos", description: "Topped with cilantro and red onion, served with spicy green sauce and limes on corn tortillas, comes with 4 tacos" , price: 9, category:"main", imgURL: "https://cdn-image.foodandwine.com/sites/default/files/styles/medium_2x/public/201005-r-xl-grilled-chicken-tacos.jpg?itok=9b50tVdU")
Item.create( name: "Chicken Fajitas", description: "Sauteed with green peppers, onions and tomatoes. Served with rice, frijoles refritos, crema Mexicana, pico de gallo and flour tortillas" , price: 16, category:"main", imgURL: "http://www.homecookingadventure.com/images/recipes/skillet_chicken_fajitas_main.jpg")
Item.create( name: "Steak Fajitas", description: "Sauteed with green peppers, onions and tomatoes. Served with rice, frijoles refritos, crema Mexicana, pico de gallo and flour tortillas" , price: 17, category:"main", imgURL: "https://www.isabeleats.com/wp-content/uploads/2018/04/easy-steak-fajitas-small-1.jpg")
Item.create( name: "Shrimp Fajitas", description: "Sauteed with green peppers, onions and tomatoes. Served with rice, frijoles refritos, crema Mexicana, pico de gallo and flour tortillas" , price: 17, category:"main", imgURL: "https://therecipecritic.com/wp-content/uploads/2017/09/0C4A0021.jpg")
Item.create( name: "Vegetales Fajitas", description: "Sauteed with green peppers, onions and tomatoes. Served with rice, frijoles refritos, crema Mexicana, pico de gallo and flour tortillas" , price: 13, category:"main", imgURL: "https://www.vegetariantimes.com/.image/t_share/MTQ3MDM3NTc4MDQ0OTA5Mjk1/fajitas1_2000_1125.jpg")
Item.create( name: "Steak Burrito",  description: "Steak stuffed into a 10\" flour tortilla with melted Monterey Jack and cheddar cheese served with rice, frijoles refritos, pico de gallo, crema Mexicana, guacamole and covered in salsa verde" , price: 15, category:"main", imgURL: "https://s3.amazonaws.com/Menu_Pic/e109ec6c-b88d-4fc0-ba95-d55c63bcc7cd_steak_burrito.jpg")
Item.create( name: "Chicken Burrito", description: "Chicken stuffed into a 10\" flour tortilla with melted Monterey Jack and cheddar cheese served with rice, frijoles refritos, pico de gallo, crema Mexicana, guacamole and covered in salsa verde" , price: 13, category:"main", imgURL: "https://images-gmi-pmc.edge-generalmills.com/ae704844-03f3-4f77-928f-863f4bf98184.jpg")
Item.create( name: "Shrimp Burrtio", description: "Shrimp stuffed into a 10\" flour tortilla with melted Monterey Jack and cheddar cheese served with rice, frijoles refritos, pico de gallo, crema Mexicana, guacamole and covered in salsa verde" , price: 16, category:"main", imgURL: "https://www.rubios.com/sites/default/files/styles/menu_item_teaser/public/menu/burrito-classic-shrimp.jpg?itok=5FjjfY8R")
Item.create( name: "Vegetales Burrito", description: "Vegetables stuffed into a 10\" flour tortilla with melted Monterey Jack and cheddar cheese served with rice, frijoles refritos, pico de gallo, crema Mexicana, guacamole and covered in salsa verde" , price: 10, category:"main", imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0A4mPdgSkUCDjCLPFLv2wvqOZ7S-o9KavLOLB2ld-0biotOlb")
Item.create( name: "Camarones Al Ajillo", description: "Shrimp sauteed and seasoned in a garlic sauce, served with white rice and sauteed vegetables" , price: 16, category:"main", imgURL: "https://ecuador.gastronomia.com/media/cache/noticia_grande/uploads/noticias/camarones%20al%20ajillo.VWxkMk45amxNYVFDYUFOcC8vMTUyMTQ4MTAzNy8.jpg")
